[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sage_vault = "64VYGx9kPeizgiqVRWGMBxbbsLV1n7YZTk8MezvpjqtZ"

[programs.localnet]
sage_vault = "64VYGx9kPeizgiqVRWGMBxbbsLV1n7YZTk8MezvpjqtZ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
